# -*- coding: utf-8 -*-
"""PandasProfilling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_ERMVaF2nHyyCBKIhKRCPBPfFwCBvZS

# Pandas Profiling

Dataset : https://www.kaggle.com/datasnaek/chess?select=games.csv

Pandas Profiling Documentations: https://pandas-profiling.github.io/pandas-profiling/docs/master/index.html

How to use Pandas-Profiling on Google Colab: https://python.plainenglish.io/how-to-use-pandas-profiling-on-google-colab-e34f34ff1c9f 

How to Import and Export Datasets in Google Colab: https://towardsdatascience.com/google-colab-import-and-export-datasets-eccf801e2971

## Install
"""

! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("games.csv")

"""## Report"""

profile = ProfileReport(df, title ="Chess Game Dataset Analysis Report",html={'style':{'full_width':True}})

profile.to_widgets()

profile.to_notebook_iframe()

